version: '3.3'

services:
  awesomeProject4:
    build: ./
    command: ./awesome_Project4
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    restart: always
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: "house_db"
      POSTGRES_USER: "Vlad_Awesome"
      POSTGRES_PASSWORD: 123
    ports:
      - "5436:5432"
